### ISSUE TITLE
welcome to nginx on debian

### ISSUE THREAD

**Issue by adrien80080** [polytan02/webapp_multi_ynh#1]
Hello ! 
j'ai installé cette application à la racine du domaine (ex :  dad.domain.tld)
mais j'ai une page NGinx : https://img.abhd.fr/ScCbzGGW/9Mc0WSY7

Je ne sais pas d'ou ça peut venir :/
Une idée ?

**Comment by polytan02** [comment]
Soucis résolu (normalement)
