### ISSUE TITLE
Removing script remove first instance

### ISSUE THREAD

**Issue by M5oul** [polytan02/webapp_multi_ynh#2]
If you want to remove second instance. Remove script [remove first install](https://github.com/polytan02/webapp_multi_ynh/blob/master/scripts/remove#L3).

I don't see how to bypass that issue.
I think something like a manifest to remove manage by moulinette which ask which domain/path instance we would remove.

**Comment by M5oul** [comment]
By the way, `rmdir` command do the job to check if the repository is empty.
`--ignore-fail-on-non-empty` option permit do not display an error message.

**Comment by polytan02** [comment]
Commit https://github.com/polytan02/webapp_multi_ynh/commit/591af6e61ed2d38be1e5b2f424d86b543c621bcc takes into account your comments. Thanks again ! :)
